### ISSUE TITLE
Docker 静态站点生成问题

### ISSUE THREAD

**Issue by yfdoor** [88250/solo#102]
solo 为 docker 安装。
正常情况下，生成静态站点没问题，可是当我把 static-site 文件夹 映射出来到宿主机磁盘的时候，再生成静态站点就会显示 “更新失败”，请问下需要怎样 debug， 宿主机的 static-site 文件夹已经开了 777 权限。

**Comment by 88250** [comment]
请看下日志。

**Comment by yfdoor** [comment]
> 请看下日志。

> [ERROR]-[2020-04-12 13:56:11]-[org.b3log.solo.processor.console.StaticSiteConsole:143]: Generates static site failed
java.io.IOException: Unable to delete directory /opt/solo/static-site.
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1623) ~[commons-io-2.6.jar:2.6]
        at org.b3log.solo.processor.console.StaticSiteConsole.genSite(StaticSiteConsole.java:102) ~[solo/:?]
        at org.b3log.solo.processor.console.StaticSiteConsole_$$_jvst731_51._d3genSite(StaticSiteConsole_$$_jvst731_51.java) ~[solo/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:117) ~[latke-core-3.2.15.jar:?]
        at org.b3log.solo.processor.console.StaticSiteConsole_$$_jvst731_51.genSite(StaticSiteConsole_$$_jvst731_51.java) ~[solo/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.b3log.latke.http.handler.InvokeHandler.handle(InvokeHandler.java:49) ~[latke-core-3.2.15.jar:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:573) ~[latke-core-3.2.15.jar:?]
        at org.b3log.solo.processor.console.ConsoleAdminAuthMidware.handle(ConsoleAdminAuthMidware.java:42) ~[solo/:?]
        at org.b3log.solo.processor.console.ConsoleAdminAuthMidware_$$_jvst731_16._d4handle(ConsoleAdminAuthMidware_$$_jvst731_16.java) ~[solo/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:117) ~[latke-core-3.2.15.jar:?]
        at org.b3log.solo.processor.console.ConsoleAdminAuthMidware_$$_jvst731_16.handle(ConsoleAdminAuthMidware_$$_jvst731_16.java) ~[solo/:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:573) [latke-core-3.2.15.jar:?]
        at org.b3log.latke.http.handler.RouteHandler.handle(RouteHandler.java:210) [latke-core-3.2.15.jar:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:573) [latke-core-3.2.15.jar:?]
        at org.b3log.solo.processor.PermalinkHandler.handle(PermalinkHandler.java:77) [solo/:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:573) [latke-core-3.2.15.jar:?]
        at org.b3log.solo.processor.InitCheckHandler.handle(InitCheckHandler.java:66) [solo/:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:573) [latke-core-3.2.15.jar:?]
        at org.b3log.solo.processor.SkinHandler.handle(SkinHandler.java:65) [solo/:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:573) [latke-core-3.2.15.jar:?]
        at org.b3log.latke.http.handler.StaticResourceHandler.handle(StaticResourceHandler.java:41) [latke-core-3.2.15.jar:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:573) [latke-core-3.2.15.jar:?]
        at org.b3log.latke.http.Dispatcher.handle(Dispatcher.java:95) [latke-core-3.2.15.jar:?]
        at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:82) [latke-core-3.2.15.jar:?]
        at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:38) [latke-core-3.2.15.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at org.b3log.latke.http.WebSocketHandler.handleHttpRequest(WebSocketHandler.java:94) [latke-core-3.2.15.jar:?]
        at org.b3log.latke.http.WebSocketHandler.channelRead0(WebSocketHandler.java:51) [latke-core-3.2.15.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) [netty-codec-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) [netty-codec-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.48.Final.jar:4.1.48.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by 88250** [comment]
看日志是因为删除生成目录失败了，看来有一定危险性，请谨慎操作啊。

**Comment by yfdoor** [comment]
> 看日志是因为删除生成目录失败了，看来有一定危险性，请谨慎操作啊。

那这个就暂时不能把 static-site 映射出来？ 后续会改进下吗？想把他映射出来写个脚本，自动同步

**Comment by 88250** [comment]
应该可以映射的，但是得小心操作。这个报错删除不了我也没搞明白，贴一下挂载命令看看。

**Comment by yfdoor** [comment]
> 应该可以映射的，但是得小心操作。这个报错删除不了我也没搞明白，贴一下挂载命令看看。

```
 -v /srv/dev-disk-by-label-disk1/nas/docker/solo/h2:/opt/solo/h2 \
 -v /srv/dev-disk-by-label-disk1/nas/docker/solo/static-site:/opt/solo/static-site \
```

**Comment by 88250** [comment]
手动进入容器试下能否读写文件和删除目录？

**Comment by yfdoor** [comment]
> 手动进入容器试下能否读写文件和删除目录？

可以的，一开始就怀疑权限的问题，后来确认过，没问题的

**Comment by 88250** [comment]
更新下最新镜像试试。

**Comment by yfdoor** [comment]
> 更新下最新镜像试试。

好吧，不过已经是最新的4.0 了。。再试下吧，不知道哪里的问题
