### ISSUE TITLE
登录github失败

### ISSUE THREAD

**Issue by Leif160519** [88250/solo#11]
![image](https://user-images.githubusercontent.com/19452903/70773897-ad2d4c80-1db3-11ea-8ec7-089e97ca02f7.png)

github账户未更改信息，前两天还可以登陆后台发布新文章来着，今天就不行，更新docker镜像后依旧如此，浏览器无痕模式登录也这样，然后我又试了几次登录，直接github404了。。。

**Comment by Leif160519** [comment]
刷新`url/start`页面发现报错：
```
[ERROR]-[2019-12-13 14:24:49]-[org.b3log.latke.http.RequestContext:554]: Handler process failed: Request [
    method=GET,
    URI=/manifest.json,
    contentType=null,
        remoteAddr=/127.0.0.1:41924,
    headers=[
        Host=127.0.0.1:8080
        Connection=close
        User-Agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
        Accept=*/*
        Sec-Fetch-Site=same-origin
        Sec-Fetch-Mode=cors
        Referer=https://leif.fun/start
        Accept-Encoding=gzip, deflate, br
        Accept-Language=zh-CN,zh;q=0.9,en;q=0.8
        content-length=0
    ]
]
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.http.handler.ContextHandleHandler.handle(ContextHandleHandler.java:39)
	at org.b3log.latke.http.RequestContext.handle(RequestContext.java:550)
	at org.b3log.latke.http.handler.BeforeHandleHandler.handle(BeforeHandleHandler.java:80)
	at org.b3log.latke.http.RequestContext.handle(RequestContext.java:550)
	at org.b3log.latke.http.handler.RouteHandler.handle(RouteHandler.java:208)
	at org.b3log.latke.http.RequestContext.handle(RequestContext.java:550)
	at org.b3log.solo.processor.PermalinkHandler.handle(PermalinkHandler.java:85)
	at org.b3log.latke.http.RequestContext.handle(RequestContext.java:550)
	at org.b3log.solo.processor.InitCheckHandler.handle(InitCheckHandler.java:65)
	at org.b3log.latke.http.RequestContext.handle(RequestContext.java:550)
	at org.b3log.solo.processor.SkinHandler.handle(SkinHandler.java:64)
	at org.b3log.latke.http.RequestContext.handle(RequestContext.java:550)
	at org.b3log.latke.http.handler.StaticResourceHandler.handle(StaticResourceHandler.java:40)
	at org.b3log.latke.http.RequestContext.handle(RequestContext.java:550)
	at org.b3log.latke.http.Dispatcher.handle(Dispatcher.java:96)
	at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:83)
	at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:37)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.b3log.latke.http.WebSocketHandler.handleHttpRequest(WebSocketHandler.java:94)
	at org.b3log.latke.http.WebSocketHandler.channelRead0(WebSocketHandler.java:51)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.json.JSONException: Expected a ',' or '}' at 224 [character 31 line 9]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.JSONObject.<init>(JSONObject.java:271)
	at org.json.JSONObject.<init>(JSONObject.java:406)
	at org.b3log.solo.processor.BlogProcessor.getPWAManifestJSON(BlogProcessor.java:119)
	at org.b3log.solo.processor.BlogProcessor_$$_jvstd33_53._d6getPWAManifestJSON(BlogProcessor_$$_jvstd33_53.java)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.processor.BlogProcessor_$$_jvstd33_53.getPWAManifestJSON(BlogProcessor_$$_jvstd33_53.java)
	... 54 more
```

**Comment by remixjc** [comment]
在非无痕状态下登录github，然后新开个浏览器标签访问你自己的网站，即可登录成功

**Comment by Leif160519** [comment]
> 在非无痕状态下登录github，然后新开个浏览器标签访问你自己的网站，即可登录成功

我刚试了一下，发现还是github404，刷新首页都报同样的java错误了

**Comment by Leif160519** [comment]
换了一台机器，点击登录后是这样
![image](https://user-images.githubusercontent.com/19452903/70774442-4872f180-1db5-11ea-9230-2f75bbec1603.png)

![image](https://user-images.githubusercontent.com/19452903/70774579-a43d7a80-1db5-11ea-93d6-00c179c64653.png)

**Comment by Leif160519** [comment]
我发现github上以前的b3log社区没了，变成了b3logos，不清楚是不是因为这个原因导致的登录失败

**Comment by 88250** [comment]
再试试看，现在应该可以登录的。

**Comment by Leif160519** [comment]
我换了一台机器，也换了别的github账号依旧登录不了，不可点

**Comment by Leif160519** [comment]
莫名其妙又好了。。。。

**Comment by 88250** [comment]
> 我换了一台机器，也换了别的github账号依旧登录不了，不可点

换个网络应该就就好了。

**Comment by TerickJojo** [comment]
> > 我换了一台机器，也换了别的github账号依旧登录不了，不可点
> 
> 换个网络应该就就好了。

遇到相同问题，换了2个浏览器，换了2个账号，换了2个地方的网络，依然404登录不上

**Comment by 88250** [comment]
@TerickJojo 请更新最新镜像。

**Comment by TerickJojo** [comment]
> @TerickJojo 请更新最新镜像。

用了这边的3.6.7成功了，那边的3.6.7有问题。。。

**Comment by 88250** [comment]
@TerickJojo 用 latest
