### ISSUE TITLE
登录不成功

### ISSUE THREAD

**Issue by loogn** [88250/solo#139]
登录之后返回：500 Internal Server Error!
login/callback?state=34S6qrH7G2n9mSRP&access_token=UxH9U36DDR3eCp9l

**Comment by 88250** [comment]
麻烦拉取最新镜像再试试看。

**Comment by loogn** [comment]
就是最新的镜像。
今天发现登录不了了，想着是更新了，更新过之后再登录发现登录方式的确变了，可是还是不行
![image](https://user-images.githubusercontent.com/967886/84236467-41d9f280-ab2a-11ea-8588-127a21d1f64f.png)

查看docker日志，异常是“用户名重复！”

**Comment by 88250** [comment]
麻烦贴一下日志。

**Comment by loogn** [comment]
ERROR]-[2020-06-10 14:40:16]-[org.b3log.solo.processor.OAuthProcessor:165]: Registers via oauth failed
org.b3log.latke.service.ServiceException: 用户名重复！
        at org.b3log.solo.service.UserMgmtService.addUser(UserMgmtService.java:280) ~[solo/:?]
        at org.b3log.solo.service.UserMgmtService_$$_jvst425_2d._d0addUser(UserMgmtService_$$_jvst425_2d.java) ~[solo/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:108) ~[latke-core-3.4.3.jar:?]
        at org.b3log.solo.service.UserMgmtService_$$_jvst425_2d.addUser(UserMgmtService_$$_jvst425_2d.java) ~[solo/:?]
        at org.b3log.solo.processor.OAuthProcessor.authCallback(OAuthProcessor.java:163) [solo/:?]
        at org.b3log.solo.processor.OAuthProcessor_$$_jvst425_51._d0authCallback(OAuthProcessor_$$_jvst425_51.java) [solo/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:108) [latke-core-3.4.3.jar:?]
        at org.b3log.solo.processor.OAuthProcessor_$$_jvst425_51.authCallback(OAuthProcessor_$$_jvst425_51.java) [solo/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.b3log.latke.http.handler.InvokeHandler.handle(InvokeHandler.java:45) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:579) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.handler.RouteHandler.handle(RouteHandler.java:200) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:579) [latke-core-3.4.3.jar:?]
        at org.b3log.solo.processor.PermalinkHandler.handle(PermalinkHandler.java:71) [solo/:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:579) [latke-core-3.4.3.jar:?]
        at org.b3log.solo.processor.InitCheckHandler.handle(InitCheckHandler.java:59) [solo/:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:579) [latke-core-3.4.3.jar:?]
        at org.b3log.solo.processor.SkinHandler.handle(SkinHandler.java:59) [solo/:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:579) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.handler.StaticResourceHandler.handle(StaticResourceHandler.java:36) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:579) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.Dispatcher.handle(Dispatcher.java:91) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:78) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:34) [latke-core-3.4.3.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at org.b3log.latke.http.WebSocketHandler.handleHttpRequest(WebSocketHandler.java:90) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.WebSocketHandler.channelRead0(WebSocketHandler.java:47) [latke-core-3.4.3.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) [netty-transport-native-epoll-4.1.49.Final-linux-x86_64.jar:4.1.49.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) [netty-transport-native-epoll-4.1.49.Final-linux-x86_64.jar:4.1.49.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-transport-native-epoll-4.1.49.Final-linux-x86_64.jar:4.1.49.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.49.Final.jar:4.1.49.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[ERROR]-[2020-06-10 14:40:27]-[org.b3log.solo.util.Skins:100]: Gets console template [error/400.ftl] failed
freemarker.template.TemplateNotFoundException: Template not found for name "error/400.ftl".
The name was interpreted by this TemplateLoader: FileTemplateLoader(baseDir="/opt/solo", canonicalBasePath="/opt/solo/").
        at freemarker.template.Configuration.getTemplate(Configuration.java:2845) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.template.Configuration.getTemplate(Configuration.java:2647) ~[freemarker-2.3.29.jar:2.3.29]
        at org.b3log.solo.util.Skins.getTemplate(Skins.java:98) [solo/:?]
        at org.b3log.solo.processor.SkinRenderer.getTemplate(SkinRenderer.java:61) [solo/:?]
        at org.b3log.latke.http.renderer.AbstractFreeMarkerRenderer.render(AbstractFreeMarkerRenderer.java:85) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.Response.sendError(Response.java:140) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.Response.sendError(Response.java:124) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.RequestContext.sendError(RequestContext.java:308) [latke-core-3.4.3.jar:?]
        at org.b3log.solo.processor.OAuthProcessor.authCallback(OAuthProcessor.java:127) [solo/:?]
        at org.b3log.solo.processor.OAuthProcessor_$$_jvst425_51._d0authCallback(OAuthProcessor_$$_jvst425_51.java) [solo/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:108) [latke-core-3.4.3.jar:?]
        at org.b3log.solo.processor.OAuthProcessor_$$_jvst425_51.authCallback(OAuthProcessor_$$_jvst425_51.java) [solo/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.b3log.latke.http.handler.InvokeHandler.handle(InvokeHandler.java:45) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:579) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.handler.RouteHandler.handle(RouteHandler.java:200) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:579) [latke-core-3.4.3.jar:?]
        at org.b3log.solo.processor.PermalinkHandler.handle(PermalinkHandler.java:71) [solo/:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:579) [latke-core-3.4.3.jar:?]
        at org.b3log.solo.processor.InitCheckHandler.handle(InitCheckHandler.java:59) [solo/:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:579) [latke-core-3.4.3.jar:?]
        at org.b3log.solo.processor.SkinHandler.handle(SkinHandler.java:59) [solo/:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:579) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.handler.StaticResourceHandler.handle(StaticResourceHandler.java:36) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.RequestContext.handle(RequestContext.java:579) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.Dispatcher.handle(Dispatcher.java:91) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:78) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:34) [latke-core-3.4.3.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at org.b3log.latke.http.WebSocketHandler.handleHttpRequest(WebSocketHandler.java:90) [latke-core-3.4.3.jar:?]
        at org.b3log.latke.http.WebSocketHandler.channelRead0(WebSocketHandler.java:47) [latke-core-3.4.3.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) [netty-transport-native-epoll-4.1.49.Final-linux-x86_64.jar:4.1.49.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) [netty-transport-native-epoll-4.1.49.Final-linux-x86_64.jar:4.1.49.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-transport-native-epoll-4.1.49.Final-linux-x86_64.jar:4.1.49.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.49.Final.jar:4.1.49.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by 88250** [comment]
感谢反馈，请重新拉取镜像部署观察，如果已经修复的话就关闭 issue 吧。

**Comment by loogn** [comment]
可以了!
