### ISSUE TITLE
在windows上使用命令启动报错

### ISSUE THREAD

**Issue by LS-LILEI** [88250/solo#252]
### 描述问题 Describe the problem

win10使用java -cp "lib/*;." org.b3log.solo.Server命令启动报错

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/b3log/solo/Server has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
### 期待的结果 Expected result
1

### 截屏或录像 Screenshot or video

1

### 版本环境 Version environment

* 版本 Version：4.4
* 操作系统 Operating system：win10/win7，jdk1.8
* 浏览器 Browser：

### 其他信息 Other information

1

**Comment by 88250** [comment]
使用 JDK11
