### ISSUE TITLE
外挂皮肤，引入静态资源不存在

### ISSUE THREAD

**Issue by AlgerFan** [88250/solo#60]
外挂皮肤，引入静态资源不存在，源码中找不到相关的引入，引用方式变了吗，日志如下

[ERROR]-[2020-02-05 05:56:11]-[org.b3log.latke.http.renderer.StaticFileRenderer:76]: Renders static file failed
java.io.FileNotFoundException: File '/opt/solo/js/comm.js' does not exist

[ERROR]-[2020-02-05 11:50:10]-[org.b3log.latke.http.renderer.StaticFileRenderer:76]: Renders static file failed
java.io.FileNotFoundException: File '/opt/solo/js/tc.js' does not exist
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:297) ~[commons-io-2.6.jar:2.6]
        at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1851) ~[commons-io-2.6.jar:2.6]
        at org.b3log.latke.http.renderer.StaticFileRenderer.render(StaticFileRenderer.java:65) [latke-core-3.2.2.jar:?]
        at org.b3log.latke.http.Dispatcher.renderResponse(Dispatcher.java:126) [latke-core-3.2.2.jar:?]
        at org.b3log.latke.http.Dispatcher.handle(Dispatcher.java:98) [latke-core-3.2.2.jar:?]

**Comment by 88250** [comment]
路径没有变，看日志应该是因为挂载路径有问题，不要挂载到 /opt/solo/ 上，要挂载到 /opt/solo/skins/ 上。

**Comment by AlgerFan** [comment]
> /opt/solo/skins/

确实是/opt/solo/skins/，以前正常使用的，3.8.0之后就出问题了

**Comment by AlgerFan** [comment]
@88250 参考Pinghsu皮肤，发现引入不太一样

**Comment by 88250** [comment]
你看下是不是这个问题 https://hacpai.com/article/1580877736555

**Comment by AlgerFan** [comment]
应该是，日志里没有错误
